### ISSUE TITLE
Only works for warmwater

### ISSUE THREAD

**Issue by lawa42** [Ludy87/ecotrend-ista#27]
Hi 
thanks for the great integration. Love this.
However, after installation it only works for the warmwater but not the heating.
After HA restart  two errors are logged:

> Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht
>
> Logger: custom_components.ecotrend_ista.sensor
> Source: custom_components/ecotrend_ista/sensor.py:241
> Integration: ecotrend ista (documentation, issues)
> First occurred: 15:11:38 (1 occurrences)
> Last logged: 15:11:38
>
> ['heating', 'warmwater']

and

> Logger: homeassistant.components.sensor
Source: custom_components/ecotrend_ista/entity.py:97
Integration: Sensor (documentation, issues)
First occurred: 15:11:38 (2 occurrences)
Last logged: 15:11:38
>
> Error adding entities for domain sensor with platform ecotrend_ista
Error while setting up ecotrend_ista platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 692, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 789, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 586, in _async_write_ha_state
    attr.update(self.extra_state_attributes or {})
  File "/config/custom_components/ecotrend_ista/entity.py", line 97, in extra_state_attributes
    "valuekwh": float(str(self._consum.get("valuekwh", "-1")).replace(",", ".")),
ValueError: could not convert string to float: 'None'

**Comment by Ludy87** [comment]
hi, I'm working on version 2 right now and I'll fix it then, thanks for your report

**Comment by lawa42** [comment]
okay I'll wait let me know if I can help by testing or similar also for #28
