### ISSUE TITLE
ValueError: could not convert string to float: 'None'

### ISSUE THREAD

**Issue by tribut** [Ludy87/ecotrend-ista#4]
Hey,

thanks a lot for taking a stab at this. I've tried adding my account, but the data for "heating" cannot be fetched. I'm getting the following backtrace (using ecotrend_ista 1.0.5):

~~~~
2022-05-08 11:42:07 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform ecotrend_ista
Traceback (most recent call last):                                                 
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities                                
    await asyncio.gather(*tasks)                                                                                                                                      
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity                   
    await entity.add_to_platform_finish()                                                                                                                             
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 810, in add_to_platform_finish                                       
    self.async_write_ha_state()                                                                                                                                       
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state                                       
    self._async_write_ha_state()                                                                                                                                      
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 574, in _async_write_ha_state                                                    
    attr.update(self.extra_state_attributes or {})                                                                                                                    
  File "/config/custom_components/ecotrend_ista/entity.py", line 68, in extra_state_attributes                                                                       
    "valuekwh": float(str(self._consum.get("valuekwh")).replace(",", ".")),                                                                                           
ValueError: could not convert string to float: 'None'                                                                                                                 
~~~~

**Comment by Ludy87** [comment]
Thanks for the report! can you please activate the [debug](https://github.com/Ludy87/ecotrend-ista#debug) and send the other messages. Apparently there are problems with your data.

**Comment by Ludy87** [comment]
Try the beta version and post the debug messages if necessary.

**Comment by Ludy87** [comment]
Thanks for helping me find and test bugs. I still don't understand why a result of `None` is possible.

Are you also seeing an error on the ecotrend-ista website?

**Comment by Ludy87** [comment]
which consumers are displayed to you on the ecotrend-ista

**Comment by Ludy87** [comment]
Next Beta: [v1.0.7-beta-2](https://github.com/Ludy87/ecotrend-ista/releases/tag/v1.0.7-beta-2)
