### ISSUE TITLE
2.0: NoneType object is not iterable

### ISSUE THREAD

**Issue by plaetzchen** [Ludy87/ecotrend-ista#61]
Getting this message, no entities are created after setup through the UI. Attached you can find the debug log.

```
2023-06-19 13:57:11.401 ERROR (MainThread) [custom_components.ecotrend_ista.coordinator] Unexpected error fetching ecotrend_ista-c343d1fceed0ec2a55ebcc44f8ce2d59 data: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecotrend_ista/coordinator.py", line 58, in _async_update_data
    await self.controller.consum_raw(select_year=[datetime.datetime.now().year])
  File "/usr/local/lib/python3.11/site-packages/pyecotrend_ista/pyecotrend_ista.py", line 49, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyecotrend_ista/pyecotrend_ista.py", line 326, in consum_raw
    for i, costs in enumerate(c_raw["costs"]):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
2023-06-19 13:57:18.621 WARNING (MainThread) [bellows.ezsp] Protocol version 12 is not supported, using version 11 instead
2023-06-19 13:57:26.663 ERROR (MainThread) [custom_components.ecotrend_ista.coordinator] Unexpected error fetching ecotrend_ista-c343d1fceed0ec2a55ebcc44f8ce2d59 data: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecotrend_ista/coordinator.py", line 58, in _async_update_data
    await self.controller.consum_raw(select_year=[datetime.datetime.now().year])
  File "/usr/local/lib/python3.11/site-packages/pyecotrend_ista/pyecotrend_ista.py", line 49, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyecotrend_ista/pyecotrend_ista.py", line 326, in consum_raw
    for i, costs in enumerate(c_raw["costs"]):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
2023-06-19 13:57:51.724 ERROR (MainThread) [custom_components.ecotrend_ista.coordinator] Unexpected error fetching ecotrend_ista-c343d1fceed0ec2a55ebcc44f8ce2d59 data: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecotrend_ista/coordinator.py", line 58, in _async_update_data
    await self.controller.consum_raw(select_year=[datetime.datetime.now().year])
  File "/usr/local/lib/python3.11/site-packages/pyecotrend_ista/pyecotrend_ista.py", line 49, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyecotrend_ista/pyecotrend_ista.py", line 326, in consum_raw
    for i, costs in enumerate(c_raw["costs"]):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
2023-06-19 13:58:34.689 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities select.wled_schreibtischlampe_preset or it is/they are currently not available
2023-06-19 13:58:37.182 ERROR (MainThread) [custom_components.ecotrend_ista.coordinator] Unexpected error fetching ecotrend_ista-c343d1fceed0ec2a55ebcc44f8ce2d59 data: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecotrend_ista/coordinator.py", line 58, in _async_update_data
    await self.controller.consum_raw(select_year=[datetime.datetime.now().year])
  File "/usr/local/lib/python3.11/site-packages/pyecotrend_ista/pyecotrend_ista.py", line 49, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyecotrend_ista/pyecotrend_ista.py", line 326, in consum_raw
    for i, costs in enumerate(c_raw["costs"]):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
2023-06-19 13:58:52.551 ERROR (MainThread) [custom_components.ecotrend_ista.coordinator] Unexpected error fetching ecotrend_ista-c343d1fceed0ec2a55ebcc44f8ce2d59 data: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecotrend_ista/coordinator.py", line 58, in _async_update_data
    await self.controller.consum_raw(select_year=[datetime.datetime.now().year])
  File "/usr/local/lib/python3.11/site-packages/pyecotrend_ista/pyecotrend_ista.py", line 49, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyecotrend_ista/pyecotrend_ista.py", line 326, in consum_raw
    for i, costs in enumerate(c_raw["costs"]):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
2023-06-19 13:58:52.564 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Ista 7SUGACB64 ' for ecotrend_ista integration not ready yet: 'NoneType' object is not iterable; Retrying in background
2023-06-19 13:58:57.838 DEBUG (MainThread) [custom_components.ecotrend_ista] Configure based on config entry c343d1fceed0ec2a55ebcc44f8ce2d59
2023-06-19 13:59:02.433 ERROR (MainThread) [custom_components.ecotrend_ista.coordinator] Unexpected error fetching ecotrend_ista-c343d1fceed0ec2a55ebcc44f8ce2d59 data: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecotrend_ista/coordinator.py", line 58, in _async_update_data
    await self.controller.consum_raw(select_year=[datetime.datetime.now().year])
  File "/usr/local/lib/python3.11/site-packages/pyecotrend_ista/pyecotrend_ista.py", line 49, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyecotrend_ista/pyecotrend_ista.py", line 326, in consum_raw
    for i, costs in enumerate(c_raw["costs"]):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
2023-06-19 13:59:02.444 DEBUG (MainThread) [custom_components.ecotrend_ista.coordinator] Finished fetching ecotrend_ista-c343d1fceed0ec2a55ebcc44f8ce2d59 data in 2.748 seconds (success: False)
2023-06-19 13:59:17.575 ERROR (MainThread) [custom_components.ecotrend_ista.coordinator] Unexpected error fetching ecotrend_ista-c343d1fceed0ec2a55ebcc44f8ce2d59 data: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecotrend_ista/coordinator.py", line 58, in _async_update_data
    await self.controller.consum_raw(select_year=[datetime.datetime.now().year])
  File "/usr/local/lib/python3.11/site-packages/pyecotrend_ista/pyecotrend_ista.py", line 49, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyecotrend_ista/pyecotrend_ista.py", line 326, in consum_raw
    for i, costs in enumerate(c_raw["costs"]):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
2023-06-19 13:59:44.952 ERROR (MainThread) [custom_components.ecotrend_ista.coordinator] Unexpected error fetching ecotrend_ista-c343d1fceed0ec2a55ebcc44f8ce2d59 data: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecotrend_ista/coordinator.py", line 58, in _async_update_data
    await self.controller.consum_raw(select_year=[datetime.datetime.now().year])
  File "/usr/local/lib/python3.11/site-packages/pyecotrend_ista/pyecotrend_ista.py", line 49, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyecotrend_ista/pyecotrend_ista.py", line 326, in consum_raw
    for i, costs in enumerate(c_raw["costs"]):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
2023-06-19 14:00:05.243 ERROR (MainThread) [frontend.js.latest.202306080] http://homeassistant.local:8123/frontend_latest/app-2AP83Z-w0C8.js:2:10848 Error: Failed to execute 'define' on 'CustomElementRegistry': the name "xiaomi-vacuum-map-card-editor" has already been used with this registry
2023-06-19 14:00:09.228 ERROR (MainThread) [root] A message handler raised an exception: 'org.bluez.Device1'.
Traceback (most recent call last):
  File "src/dbus_fast/message_bus.py", line 811, in dbus_fast.message_bus.BaseMessageBus._process_message
  File "/usr/local/lib/python3.11/site-packages/bleak/backends/bluezdbus/manager.py", line 854, in _parse_msg
    condition_callback()
  File "/usr/local/lib/python3.11/site-packages/bleak/backends/bluezdbus/manager.py", line 709, in callback
    self._properties[device_path][defs.DEVICE_INTERFACE][property_name]
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'org.bluez.Device1'

2023-06-19 14:00:14.455 ERROR (MainThread) [root] A message handler raised an exception: 'org.bluez.Device1'.
Traceback (most recent call last):
  File "src/dbus_fast/message_bus.py", line 811, in dbus_fast.message_bus.BaseMessageBus._process_message
  File "/usr/local/lib/python3.11/site-packages/bleak/backends/bluezdbus/manager.py", line 854, in _parse_msg
    condition_callback()
  File "/usr/local/lib/python3.11/site-packages/bleak/backends/bluezdbus/manager.py", line 709, in callback
    self._properties[device_path][defs.DEVICE_INTERFACE][property_name]
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'org.bluez.Device1'

2023-06-19 14:00:14.597 ERROR (MainThread) [root] A message handler raised an exception: 'org.bluez.Device1'.
Traceback (most recent call last):
  File "src/dbus_fast/message_bus.py", line 811, in dbus_fast.message_bus.BaseMessageBus._process_message
  File "/usr/local/lib/python3.11/site-packages/bleak/backends/bluezdbus/manager.py", line 854, in _parse_msg
    condition_callback()
  File "/usr/local/lib/python3.11/site-packages/bleak/backends/bluezdbus/manager.py", line 709, in callback
    self._properties[device_path][defs.DEVICE_INTERFACE][property_name]
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'org.bluez.Device1'
```

Home Assistant 2023.6.2
Supervisor 2023.06.2
Operating System 10.3
Frontend 20230608.0 - latest

**Comment by plaetzchen** [comment]
Sorry but same issue, even with a delete a re-setup

**Comment by Ludy87** [comment]
It can't be the same error, the lib now checks if an entry is present, which was not the case before.
