### ISSUE TITLE
Not working after upgradfe to 2.0.0 and 2.0.1

### ISSUE THREAD

**Issue by lawa42** [Ludy87/ecotrend-ista#67]
If you send instructions I can try to debug. The new 2.0.[0|1] version doesn't work, Just says retry setup. It does show a device name (looks like random numbers and letters: 6GFH7....)

**Comment by Ludy87** [comment]
I can't help without more information, a screenshot would be a first approach, a log output would also be great.

**Comment by dieneuser** [comment]
I have the same error, like @lawa42 described. 

![image](https://github.com/Ludy87/ecotrend-ista/assets/28509955/c4cce483-0826-4ef7-998a-cc70e7513c98)

`Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.ecotrend_ista.coordinator
Source: custom_components/ecotrend_ista/coordinator.py:58
Integration: ista EcoTrend (documentation, issues)
First occurred: 19. Juni 2023 um 18:04:32 (12 occurrences)
Last logged: 08:01:38

Unexpected error fetching ecotrend_ista-d61e4ad8c93271fd31e85aeb0010169f data: 'NoneType' object is not iterable
Unexpected error fetching ecotrend_ista-1a2a7dd57765aa2d412f76051a88e6a3 data: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecotrend_ista/coordinator.py", line 58, in _async_update_data
    await self.controller.consum_raw(select_year=[datetime.datetime.now().year])
  File "/usr/local/lib/python3.11/site-packages/pyecotrend_ista/pyecotrend_ista.py", line 49, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyecotrend_ista/pyecotrend_ista.py", line 329, in consum_raw
    for i, costs in enumerate(c_raw.get("costs", None)):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
`

**Comment by Ludy87** [comment]
Danke @dieneuser damit kann ich arbeiten und die lib fixen

**Comment by Firehome2022** [comment]
Hallo gleicher Fehler auch in meiner Installation:
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.ecotrend_ista.coordinator
Source: custom_components/ecotrend_ista/coordinator.py:58
Integration: ista EcoTrend (documentation, issues)
First occurred: 15:29:35 (18 occurrences)
Last logged: 15:44:37

Unexpected error fetching ecotrend_ista-440848e20b53275205212b1416725d42 data: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecotrend_ista/coordinator.py", line 58, in _async_update_data
    await self.controller.consum_raw(select_year=[datetime.datetime.now().year])
  File "/usr/local/lib/python3.11/site-packages/pyecotrend_ista/pyecotrend_ista.py", line 49, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyecotrend_ista/pyecotrend_ista.py", line 329, in consum_raw
    for i, costs in enumerate(c_raw.get("costs", None)):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable

Freue mich auf die neue Version in der der Fehler behoben ist! ;-)
