### ISSUE TITLE
Fehler nach gerade veröffentlichtem Update noch vorhanden

### ISSUE THREAD

**Issue by Firehome2022** [Ludy87/ecotrend-ista#70]
Leider sieht es bei mir nach dem Update gerade genau so aus wie heute Nachmittag!

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.ecotrend_ista.coordinator
Source: custom_components/ecotrend_ista/coordinator.py:82
Integration: ista EcoTrend (documentation, issues)
First occurred: 18:56:24 (10 occurrences)
Last logged: 19:00:37

Unexpected error fetching ecotrend_ista-440848e20b53275205212b1416725d42 data: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecotrend_ista/coordinator.py", line 82, in _async_update_data
    await self.controller.consum_raw(select_year=[datetime.datetime.now().year])
  File "/usr/local/lib/python3.11/site-packages/pyecotrend_ista/pyecotrend_ista.py", line 49, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyecotrend_ista/pyecotrend_ista.py", line 329, in consum_raw
    for i, costs in enumerate(c_raw.get("costs", [])):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable

Vielleicht könnt ihr ja noch mal gucken ob ihr noch was findet

**Comment by Ludy87** [comment]
@Firehome2022 & @lawa42 Has the error been fixed? Or are there other errors.

**Comment by Firehome2022** [comment]
Hallo bei mir ist der Fehler wie oben geschrieben noch da!
Hatte vorhin auch noch einen weiteren Fehler im LOG:
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant.config_entries
Source: custom_components/ecotrend_ista/coordinator.py:75
Integration: ista EcoTrend (documentation, issues)
First occurred: 20. Juni 2023 um 20:00:34 (1 occurrences)
Last logged: 20. Juni 2023 um 20:00:34

Error setting up entry Ista E8YC7425U for ecotrend_ista
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecotrend_ista/__init__.py", line 52, in async_setup_entry
    await coordinator.init()
  File "/config/custom_components/ecotrend_ista/coordinator.py", line 75, in init
    await self.controller.login()
  File "/usr/local/lib/python3.11/site-packages/pyecotrend_ista/pyecotrend_ista.py", line 214, in login
    await self.__setAccount()
  File "/usr/local/lib/python3.11/site-packages/pyecotrend_ista/pyecotrend_ista.py", line 153, in __setAccount
    async with session.get(ACCOUNT_URL, headers=self._header) as response:
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 894, in start
    with self._timer:
  File "/usr/local/lib/python3.11/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
TimeoutError


Der Oben genannte ist aber immer noch da!
