### ISSUE TITLE
New upstream error while fetching data 

### ISSUE THREAD

**Issue by pomeloy** [Ludy87/ecotrend-ista#74]
ecotrend-ista version: 2.0.4
Home Assistant version: 2023.6.3

Error log:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecotrend_ista/coordinator.py", line 82, in _async_update_data
    await self.controller.consum_raw(select_year=[datetime.datetime.now().year])
  File "/usr/local/lib/python3.11/site-packages/pyecotrend_ista/pyecotrend_ista.py", line 49, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyecotrend_ista/pyecotrend_ista.py", line 500, in consum_raw
    if costsByEnergyType["comparedCost"]["smiley"] in ["MAD", "EQUAL"]:
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

The Ista website currently does not display the heating costs: 

> Heizung: Aktuell keine Werte vorhanden

**Comment by pomeloy** [comment]
Thank you for taking the time to take a look at this. 

The new commit (ecotrend-ista version: 2.0.6) introduced another error:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecotrend_ista/coordinator.py", line 82, in _async_update_data
    _consum_raw: dict[str, Any] = await self.controller.consum_raw(select_year=[datetime.datetime.now().year])
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyecotrend_ista/pyecotrend_ista.py", line 49, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyecotrend_ista/pyecotrend_ista.py", line 484, in consum_raw
    or "smiley" not in costsByEnergyType["comparedCost"]
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```

Do you need any additional info to fix this?
