### ISSUE TITLE
Still upstream error while fetching data

### ISSUE THREAD

**Issue by pomeloy** [Ludy87/ecotrend-ista#77]
Thank you for taking the time to look into #74 

The new commit (ecotrend-ista version: 2.0.6) introduced another error:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecotrend_ista/coordinator.py", line 82, in _async_update_data
    _consum_raw: dict[str, Any] = await self.controller.consum_raw(select_year=[datetime.datetime.now().year])
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyecotrend_ista/pyecotrend_ista.py", line 49, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyecotrend_ista/pyecotrend_ista.py", line 484, in consum_raw
    or "smiley" not in costsByEnergyType["comparedCost"]
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```

Do you need any additional info to fix this?

**Comment by Ludy87** [comment]
Hello could you provide the file from your www folder if you have it.

The file has the following syntax ecotrend_ista_#####.json

**Comment by pomeloy** [comment]
There is no ecotrend_ista_#####.json file on my home assistant installation.

**Comment by Ludy87** [comment]
Very strange, isn't there a www folder in the config folder?

New release:
https://github.com/Ludy87/ecotrend-ista/releases

**Comment by pomeloy** [comment]
Sorry, I was still using 2.0.6 at the time of the comment. Just updated and now there is a json file and it's working. Thanks a lot!

Just for the record, here are my json file contents:

```
{
    "consum_types": [
        "warmwater",
        "heating"
    ],
    "combined_data": null,
    "total_additional_values": {
        "heating": ***,
        "warmwater": ***,
        "water": null,
        "ww": "m\u00b3",
        "w": null,
        "h": "kWh"
    },
    "total_additional_custom_values": {
        "heating": ***,
        "warmwater": ***,
        "water": null,
        "ww": "kWh",
        "w": null,
        "h": "Einheiten"
    },
    "last_value": {
        "heating": ***,
        "warmwater": ***,
        "water": null,
        "month": 5,
        "year": 2023,
        "ww": "m\u00b3",
        "w": null,
        "h": "kWh"
    },
    "last_custom_value": {
        "heating": ***,
        "warmwater": ***,
        "water": null,
        "month": 5,
        "year": 2023,
        "ww": "kWh",
        "w": null,
        "h": "Einheiten"
    },
    "all_dates": null,
    "sum_by_year": {
        "heating": {
            "2023": ***
        },
        "warmwater": {
            "2023": ***
        },
        "water": null,
        "ww": "m\u00b3",
        "w": null,
        "h": "kWh"
    },
    "last_costs": {
        "heating": null,
        "warmwater": null,
        "water": null,
        "month": 5,
        "year": 2023,
        "unit": null
    }
}
```

All values (***) are correct. Just out of interest, the year-to-date sum of the heating consumption is calculated from the single entries, no? Are there plans to actually make it available in the frontend?

**Comment by Ludy87** [comment]
If that's what you want, I can see if I can install it
